### ISSUE TITLE
Improve JSDoc

### ISSUE THREAD

**Issue by izqalan** [izqalan/bnm-api#4]
### Issue
Add annotation to methods and parameters using [JSDoc](https://github.com/jsdoc/jsdoc).

### Additional Reference
[BNM open API Documentation](https://api.bnm.gov.my/portal)

**Comment by staghouse** [comment]
i believe JSDoc is abandoned for ESDoc

**Comment by mohammadanang** [comment]
@izqalan please check my PR, thanks in advance

**Comment by TheBrown** [comment]
Hi, I'm interested in this. how can I get started?

**Comment by izqalan** [comment]
@TheBrown could you add a description for what each function does?

### for example
```js
/**
 * @function baseRate - Current Base Rates and Base Lending Rates..
 */
```
You can refer [Bank Negara Malaysia Open API Docs](https://api.bnm.gov.my/portal#tag/Base-RatesBLREffective-LR) for descriptions.

**Comment by dipanshubhola1009** [comment]
hii, I m interested what i can do for you?
