### ISSUE TITLE
Exchange Rates unit test is failling

### ISSUE THREAD

**Issue by AzrizHaziq** [izqalan/bnm-api#8]
**Describe the bug**
Run `yarn test` and there is error on these unit test.
![image](https://user-images.githubusercontent.com/9023187/95150983-1efbda00-07bc-11eb-86fc-0b95ebc99caa.png)

**Desktop (please complete the following information):**
- npm: 6.14.6
- node: 10.22.1

I've tried to solve the error but could not do it because i'm thinking that request/response structure might have been update by BNM dev team.

**Comment by msomji** [comment]
Yes I think this is a bug with the BNM API. Though the redoc links to 
https://api.bnm.gov.my/portal#operation/ERLatestCurr
using postman to hit `GET https://api.bnm.gov.my/public/exchange-rate/USD` returns a 404 as well

**Comment by izqalan** [comment]
@msomji @AzrizHaziq good find! I'll get in contact with them.
